modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3.0"
[[mods]]
modId="slimebreeder"
version="${file.jarVersion}"
displayName="SlimeBreeder Mod"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"

description='''
Have some lorem ipsum.
'''

[[dependencies.slimebreeder]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.slimebreeder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
